# Grundlagen der Multimediatechnik
## Wintersemester 2021/2022

## Übungslatt 8
<b>Wichtig</b>: Bitte kennzeichnen Sie Ihre Abgabe mit Ihrem Namen und dem Namen Ihres Übungspartners. <br>
Laden Sie bitte Ihre Abgabe als PDF-/ZIP-Datei auf der ILIAS-Plattform hoch. Andere Dateiformate sowie Scans von handgeschriebenen Abgaben werden nicht gewertet. Achten Sie darauf, nur kompilierbaren, kommentierten Code abzugeben. Nicht-kompilierbarer Code wird mit <b>0 Punkten</b> bewertet! \\
Alle Abgaben müussen folgender Namenskonvention entsprechen:  `gmt_uebungXX_nachname1_nachname2.format` <br>
Im Falle Ihres Notebooks: `gmt_uebungXX_nachname1_nachmame2.ipynb`

In [1]:
# imports

import numpy as np

### Aufgabe 4 - Diskrete Kosinustransformation (5 Punkte)
Gegeben sei die Matrix $w$ im Ortsraum, die einen $8\times 8$ Pixelblock darstellt:
$$w = \begin{pmatrix}
      25 & 42 & 55 & 64 & 68 & 68 & 64 & 55 \\
      35 & 56 & 72 & 83 & 88 & 88 & 83 & 72 \\
      42 & 66 & 84 & 96 & 102 & 102 & 96 & 84 \\
      46 & 72 & 92 & 104 & 111 & 111 & 104 & 92 \\
      48 & 74 & 94 & 108 & 114 & 114 & 108 & 94 \\
      47 & 73 & 92 & 105 & 112 & 112 & 105 & 92 \\
      43 & 67 & 85 & 98 & 104 & 104 & 98 & 85 \\
      36 & 58 & 74 & 85 & 90 & 90 & 85 & 74
    \end{pmatrix}$$
Die Werte der Ergebnismatrix im Frequenzraum können mit folgender Formel aus der Vorlesung berechnet werden:
 $$ C_{u,v} = \alpha(u) \cdot \alpha(v) \cdot \sum_{m=0}^7
  \sum_{n=0}^7 w_{m,n} \cdot \cos\frac{(2m+1)\pi u}{16} \cdot
  \cos\frac{(2n+1)\pi v}{16} $$
Wobei
  $$ \alpha(x) = \begin{cases}
   \sqrt{\frac{1}{8}}, & \text{wenn}\ x = 0\\
    \sqrt{\frac{2}{8}} & \text{sonst.}
  \end{cases} $$
Berechnen Sie die Werte der Ergebnismatrix.

In [2]:
# TODO
w = np.array( [ [25, 42, 55, 64, 68, 68, 64, 55],
                [35, 56, 72, 83, 88, 88, 83, 72],
                [42, 66, 84, 96, 102, 102, 96, 84],
                [46, 72, 92, 104, 111, 111, 104, 92],
                [48, 74, 94, 108, 114, 114, 108, 94],
                [47, 73, 92, 105, 112, 112, 105, 92],
                [43, 67, 85, 98, 104, 104, 98, 85],
                [36, 58, 74, 85, 90, 90, 85, 74]
              ])

In [3]:
def calcDCT(matrix):
    # ----helper functions----
    def clamp(x):
        result = np.sqrt(2/8)
        if x == 0:
            result = np.sqrt(1/8)
        return result
    def calcCos(oldPos, newPos):
         return np.cos( ((2*oldPos+1) * np.pi * newPos) * 1/16 )
    # ----end of helper functions----

    dctMatrix = np.zeros( (8,8),int)

    # position of dct-matrix
    for u in range(8):
        for v in range(8):

            temp = 0
            # position of input matrix
            for m in range(8):
                for n in range(8):
                    pixel = w[m,n]
                    temp += pixel * calcCos(m,u) * calcCos(n,v)

            weight = clamp(u) * clamp(v)
            dctMatrix[u,v] = weight * temp

    return dctMatrix

In [4]:
dct = calcDCT(w)
print("Original:",w,"DCT:",dct,sep='\n')

Original:
[[ 25  42  55  64  68  68  64  55]
 [ 35  56  72  83  88  88  83  72]
 [ 42  66  84  96 102 102  96  84]
 [ 46  72  92 104 111 111 104  92]
 [ 48  74  94 108 114 114 108  94]
 [ 47  73  92 105 112 112 105  92]
 [ 43  67  85  98 104 104  98  85]
 [ 36  58  74  85  90  90  85  74]]
DCT:
[[ 648 -106 -104  -10  -23   -2   -7    0]
 [ -49    6    6    0    1    0    0    0]
 [ -84   11   11    1    2    0    0    0]
 [  -4    0    0    0    0    0    0    0]
 [ -18    2    2    0    0    0    0    0]
 [  -1    0    0    0    0    0    0    0]
 [  -6    1    1    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]]
